<a href="https://colab.research.google.com/github/Marlon-Sbardelatti/machine-learning/blob/extra/extra/apriori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=cba39bd70b73535a21154f1daa74202fa20b8618d14facc05359cb0da6880c6f
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

**1. Acompanhe o vídeo abaixo para implementar o algoritmo de Regras de Associação do Mercado.**

In [5]:
import pandas as pd
from apyori import apriori

market_data = pd.read_csv('mercado.csv', header = None)

transactions = []
for i in range(0, 10):
  transactions.append([str(market_data.values[i, j]) for j in range(0, 4)])

rules = apriori(transactions)

results = list(rules)
results

[RelationRecord(items=frozenset({'arroz'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'arroz'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cafe'}), confidence=0.3, lift=1.0)]),
 RelationRecord(items=frozenset({'cerveja'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cerveja'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'feijao'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'feijao'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'leite'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'manteiga'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'manteiga'}), confidence=0.5, lift=1.0)]),
 RelationRecord(items=frozenset({'nan'}), support=0.8, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan'}), confidence=0.8, lift=1.0)]),
 RelationRecord(items=frozenset({'pao'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'pao'}), confidence=0.5, lift=1.0)]),
 RelationRecord(items=frozenset({'arroz', 'feijao'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'arroz', 'feijao'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'arroz'}), items_add=frozenset({'feijao'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'feijao'}), items_add=frozenset({'arroz'}), confidence=0.5, lift=2.5)]),
 RelationRecord(items=frozenset({'arroz', 'nan'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'arroz', 'nan'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'arroz'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'arroz'}), confidence=0.25, lift=1.25)]),
 RelationRecord(items=frozenset({'leite', 'cafe'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'cafe'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'leite'}), confidence=0.33333333333333337, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'cafe'}), confidence=0.5, lift=1.6666666666666667)]),
 RelationRecord(items=frozenset({'manteiga', 'cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'manteiga', 'cafe'}), confidence=0.3, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'cafe'}), confidence=0.6, lift=2.0)]),
 RelationRecord(items=frozenset({'nan', 'cafe'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'cafe'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'nan'}), confidence=0.6666666666666667, lift=0.8333333333333334), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'cafe'}), confidence=0.25, lift=0.8333333333333334)]),
 RelationRecord(items=frozenset({'pao', 'cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'pao', 'cafe'}), confidence=0.3, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'cafe'}), confidence=0.6, lift=2.0)]),
 RelationRecord(items=frozenset({'leite', 'cerveja'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'cerveja'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'leite'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'cerveja'}), confidence=0.5, lift=2.5)]),
 RelationRecord(items=frozenset({'manteiga', 'cerveja'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'manteiga', 'cerveja'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'manteiga'}), confidence=0.5, lift=1.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'cerveja'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'cerveja', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cerveja', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'nan'}), confidence=0.5, lift=0.625), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'cerveja'}), confidence=0.125, lift=0.625)]),
 RelationRecord(items=frozenset({'cerveja', 'pao'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cerveja', 'pao'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'pao'}), confidence=0.5, lift=1.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'cerveja'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'feijao', 'nan'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'feijao', 'nan'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'feijao'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'feijao'}), confidence=0.25, lift=1.25)]),
 RelationRecord(items=frozenset({'leite', 'manteiga'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'manteiga'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'leite'}), confidence=0.4, lift=2.0)]),
 RelationRecord(items=frozenset({'leite', 'pao'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'pao'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'leite'}), confidence=0.4, lift=2.0)]),
 RelationRecord(items=frozenset({'manteiga', 'nan'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'manteiga', 'nan'}), confidence=0.3, lift=1.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'nan'}), confidence=0.6, lift=0.7499999999999999), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'manteiga'}), confidence=0.37499999999999994, lift=0.7499999999999999)]),
 RelationRecord(items=frozenset({'manteiga', 'pao'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'manteiga', 'pao'}), confidence=0.4, lift=1.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'pao'}), confidence=0.8, lift=1.6), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'manteiga'}), confidence=0.8, lift=1.6)]),
 RelationRecord(items=frozenset({'nan', 'pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'pao'}), confidence=0.3, lift=1.0), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'pao'}), confidence=0.37499999999999994, lift=0.7499999999999999), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'nan'}), confidence=0.6, lift=0.7499999999999999)]),
 RelationRecord(items=frozenset({'arroz', 'feijao', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'arroz', 'feijao', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'arroz'}), items_add=frozenset({'feijao', 'nan'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'feijao'}), items_add=frozenset({'arroz', 'nan'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'arroz', 'feijao'}), confidence=0.125, lift=1.25), OrderedStatistic(items_base=frozenset({'arroz', 'feijao'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'arroz', 'nan'}), items_add=frozenset({'feijao'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'feijao', 'nan'}), items_add=frozenset({'arroz'}), confidence=0.5, lift=2.5)]),
 RelationRecord(items=frozenset({'leite', 'cafe', 'manteiga'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'cafe', 'manteiga'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'leite', 'manteiga'}), confidence=0.33333333333333337, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'manteiga', 'cafe'}), confidence=0.5, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'leite', 'cafe'}), confidence=0.2, lift=2.0), OrderedStatistic(items_base=frozenset({'leite', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga', 'cafe'}), items_add=frozenset({'leite'}), confidence=0.33333333333333337, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'leite', 'manteiga'}), items_add=frozenset({'cafe'}), confidence=0.5, lift=1.6666666666666667)]),
 RelationRecord(items=frozenset({'leite', 'pao', 'cafe'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'pao', 'cafe'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'leite', 'pao'}), confidence=0.33333333333333337, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'pao', 'cafe'}), confidence=0.5, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'leite', 'cafe'}), confidence=0.2, lift=2.0), OrderedStatistic(items_base=frozenset({'leite', 'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'leite'}), confidence=0.33333333333333337, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'leite', 'pao'}), items_add=frozenset({'cafe'}), confidence=0.5, lift=1.6666666666666667)]),
 RelationRecord(items=frozenset({'manteiga', 'nan', 'cafe'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'manteiga', 'nan', 'cafe'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga', 'nan'}), confidence=0.6666666666666667, lift=2.2222222222222228), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'nan', 'cafe'}), confidence=0.4, lift=2.0), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'manteiga', 'cafe'}), confidence=0.25, lift=0.8333333333333334), OrderedStatistic(items_base=frozenset({'manteiga', 'cafe'}), items_add=frozenset({'nan'}), confidence=0.6666666666666667, lift=0.8333333333333334), OrderedStatistic(items_base=frozenset({'nan', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga', 'nan'}), items_add=frozenset({'cafe'}), confidence=0.6666666666666667, lift=2.2222222222222228)]),
 RelationRecord(items=frozenset({'manteiga', 'pao', 'cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'manteiga', 'pao', 'cafe'}), confidence=0.3, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga', 'pao'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'pao', 'cafe'}), confidence=0.6, lift=2.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'manteiga', 'cafe'}), confidence=0.6, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga', 'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga', 'pao'}), items_add=frozenset({'cafe'}), confidence=0.7499999999999999, lift=2.4999999999999996)]),
 RelationRecord(items=frozenset({'nan', 'cafe', 'pao'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'cafe', 'pao'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'nan', 'pao'}), confidence=0.6666666666666667, lift=2.2222222222222228), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'pao', 'cafe'}), confidence=0.25, lift=0.8333333333333334), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'nan', 'cafe'}), confidence=0.4, lift=2.0), OrderedStatistic(items_base=frozenset({'nan', 'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'nan'}), confidence=0.6666666666666667, lift=0.8333333333333334), OrderedStatistic(items_base=frozenset({'nan', 'pao'}), items_add=frozenset({'cafe'}), confidence=0.6666666666666667, lift=2.2222222222222228)]),
 RelationRecord(items=frozenset({'leite', 'cerveja', 'manteiga'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'cerveja', 'manteiga'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'leite', 'manteiga'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'manteiga', 'cerveja'}), confidence=0.5, lift=5.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'leite', 'cerveja'}), confidence=0.2, lift=2.0), OrderedStatistic(items_base=frozenset({'leite', 'cerveja'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga', 'cerveja'}), items_add=frozenset({'leite'}), confidence=1.0, lift=5.0), OrderedStatistic(items_base=frozenset({'leite', 'manteiga'}), items_add=frozenset({'cerveja'}), confidence=0.5, lift=2.5)]),
 RelationRecord(items=frozenset({'leite', 'cerveja', 'pao'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'cerveja', 'pao'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'leite', 'pao'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'cerveja', 'pao'}), confidence=0.5, lift=5.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'leite', 'cerveja'}), confidence=0.2, lift=2.0), OrderedStatistic(items_base=frozenset({'leite', 'cerveja'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'cerveja', 'pao'}), items_add=frozenset({'leite'}), confidence=1.0, lift=5.0), OrderedStatistic(items_base=frozenset({'leite', 'pao'}), items_add=frozenset({'cerveja'}), confidence=0.5, lift=2.5)]),
 RelationRecord(items=frozenset({'manteiga', 'cerveja', 'pao'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'manteiga', 'cerveja', 'pao'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'manteiga', 'pao'}), confidence=0.5, lift=1.25), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'cerveja', 'pao'}), confidence=0.2, lift=2.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'manteiga', 'cerveja'}), confidence=0.2, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga', 'cerveja'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'cerveja', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga', 'pao'}), items_add=frozenset({'cerveja'}), confidence=0.25, lift=1.25)]),
 RelationRecord(items=frozenset({'leite', 'pao', 'manteiga'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'pao', 'manteiga'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'manteiga', 'pao'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'leite', 'pao'}), confidence=0.4, lift=2.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'leite', 'manteiga'}), confidence=0.4, lift=2.0), OrderedStatistic(items_base=frozenset({'leite', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'leite', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga', 'pao'}), items_add=frozenset({'leite'}), confidence=0.5, lift=2.5)]),
 RelationRecord(items=frozenset({'manteiga', 'nan', 'pao'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'manteiga', 'nan', 'pao'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'nan', 'pao'}), confidence=0.4, lift=1.3333333333333335), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'manteiga', 'pao'}), confidence=0.25, lift=0.625), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'manteiga', 'nan'}), confidence=0.4, lift=1.3333333333333335), OrderedStatistic(items_base=frozenset({'manteiga', 'nan'}), items_add=frozenset({'pao'}), confidence=0.6666666666666667, lift=1.3333333333333335), OrderedStatistic(items_base=frozenset({'manteiga', 'pao'}), items_add=frozenset({'nan'}), confidence=0.5, lift=0.625), OrderedStatistic(items_base=frozenset({'nan', 'pao'}), items_add=frozenset({'manteiga'}), confidence=0.6666666666666667, lift=1.3333333333333335)]),

**2. Utilize a base de dados maior (mercado2) que apresenta o histórico de compras de um supermercado francês em 1 semana. Teste o seu algoritmo e responda as seguintes perguntas:**

In [6]:
market_data_2 = pd.read_csv('mercado2.csv', header = None)

**a) Vamos supor que você quer extrair Regras da Associação para os produtos que são vendidos pelo menos quatro vezes ao dia, ou seja, 28 vezes por semana (4*7). Adicione o valor de suporte de acordo com o problema. Execute o algoritmo e responda qual é o resultado.**

In [8]:
transactions = []
for i in range(0, 10):
  transactions.append([str(market_data_2.values[i, j]) for j in range(0, 4)])

support = 28 / len(market_data_2.values)

rules = apriori(transactions, min_support = support)

results = list(rules)
results

[RelationRecord(items=frozenset({'almonds'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'almonds'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'avocado'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'avocado'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'burgers'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'burgers'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'chutney'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'chutney'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'eggs'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'eggs'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'energy bar'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'energy bar'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'french fries'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'french fries'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'frozen vegetables'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'frozen vegetables'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'green tea'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'green tea'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'light cream'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'light cream'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'low fat yogurt'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'low fat yogurt'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'meatballs'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'meatballs'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'milk'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'milk'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'mineral water'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'mineral water'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'nan'}), support=0.8, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan'}), confidence=0.8, lift=1.0)]),
 RelationRecord(items=frozenset({'shallot'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'shallot'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'shrimp'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'shrimp'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'soup'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'soup'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'spaghetti'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'spaghetti'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'turkey'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'turkey'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'vegetables mix'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'vegetables mix'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'whole wheat pasta'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'whole wheat pasta'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'whole wheat rice'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'whole wheat rice'}), confidence=0.1, lift=1.0)]),
 RelationRecord(items=frozenset({'avocado', 'almonds'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'avocado', 'almonds'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'avocado'}), confidence=1.0, lift=5.0), OrderedStatistic(items_base=frozenset({'avocado'}), items_add=frozenset({'almonds'}), confidence=0.5, lift=5.0)]),
 RelationRecord(items=frozenset({'almonds', 'shrimp'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'almonds', 'shrimp'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'shrimp'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'shrimp'}), items_add=frozenset({'almonds'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'vegetables mix', 'almonds'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'vegetables mix', 'almonds'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'vegetables mix'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'vegetables mix'}), items_add=frozenset({'almonds'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'avocado', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'avocado', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'avocado'}), items_add=frozenset({'nan'}), confidence=0.5, lift=0.625), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'avocado'}), confidence=0.125, lift=0.625)]),
 RelationRecord(items=frozenset({'avocado', 'shrimp'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'avocado', 'shrimp'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'avocado'}), items_add=frozenset({'shrimp'}), confidence=0.5, lift=5.0), OrderedStatistic(items_base=frozenset({'shrimp'}), items_add=frozenset({'avocado'}), confidence=1.0, lift=5.0)]),
 RelationRecord(items=frozenset({'avocado', 'turkey'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'avocado', 'turkey'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'avocado'}), items_add=frozenset({'turkey'}), confidence=0.5, lift=5.0), OrderedStatistic(items_base=frozenset({'turkey'}), items_add=frozenset({'avocado'}), confidence=1.0, lift=5.0)]),
 RelationRecord(items=frozenset({'vegetables mix', 'avocado'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'vegetables mix', 'avocado'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'avocado'}), items_add=frozenset({'vegetables mix'}), confidence=0.5, lift=5.0), OrderedStatistic(items_base=frozenset({'vegetables mix'}), items_add=frozenset({'avocado'}), confidence=1.0, lift=5.0)]),
 RelationRecord(items=frozenset({'burgers', 'eggs'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'burgers', 'eggs'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'burgers'}), items_add=frozenset({'eggs'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'eggs'}), items_add=frozenset({'burgers'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'burgers', 'meatballs'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'burgers', 'meatballs'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'burgers'}), items_add=frozenset({'meatballs'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'meatballs'}), items_add=frozenset({'burgers'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'burgers', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'burgers', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'burgers'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'burgers'}), confidence=0.125, lift=1.25)]),
 RelationRecord(items=frozenset({'chutney', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'chutney', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'chutney'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'chutney'}), confidence=0.125, lift=1.25)]),
 RelationRecord(items=frozenset({'eggs', 'meatballs'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'eggs', 'meatballs'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'eggs'}), items_add=frozenset({'meatballs'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'meatballs'}), items_add=frozenset({'eggs'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'eggs', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'eggs', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'eggs'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'eggs'}), confidence=0.125, lift=1.25)]),
 RelationRecord(items=frozenset({'milk', 'energy bar'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'milk', 'energy bar'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'energy bar'}), items_add=frozenset({'milk'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'milk'}), items_add=frozenset({'energy bar'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'mineral water', 'energy bar'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'mineral water', 'energy bar'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'energy bar'}), items_add=frozenset({'mineral water'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'mineral water'}), items_add=frozenset({'energy bar'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'whole wheat rice', 'energy bar'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'whole wheat rice', 'energy bar'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'energy bar'}), items_add=frozenset({'whole wheat rice'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'whole wheat rice'}), items_add=frozenset({'energy bar'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'nan', 'french fries'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'french fries'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'french fries'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'french fries'}), confidence=0.25, lift=1.25)]),
 RelationRecord(items=frozenset({'whole wheat pasta', 'french fries'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'whole wheat pasta', 'french fries'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'french fries'}), items_add=frozenset({'whole wheat pasta'}), confidence=0.5, lift=5.0), OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'french fries'}), confidence=1.0, lift=5.0)]),
 RelationRecord(items=frozenset({'green tea', 'frozen vegetables'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'green tea', 'frozen vegetables'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'frozen vegetables'}), items_add=frozenset({'green tea'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'green tea'}), items_add=frozenset({'frozen vegetables'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'nan', 'frozen vegetables'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'frozen vegetables'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'frozen vegetables'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'frozen vegetables'}), confidence=0.125, lift=1.25)]),
 RelationRecord(items=frozenset({'spaghetti', 'frozen vegetables'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'spaghetti', 'frozen vegetables'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'frozen vegetables'}), items_add=frozenset({'spaghetti'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'spaghetti'}), items_add=frozenset({'frozen vegetables'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'nan', 'green tea'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'green tea'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'green tea'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'green tea'}), confidence=0.125, lift=1.25)]),
 RelationRecord(items=frozenset({'spaghetti', 'green tea'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'spaghetti', 'green tea'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'green tea'}), items_add=frozenset({'spaghetti'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'spaghetti'}), items_add=frozenset({'green tea'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'light cream', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'light cream', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'light cream'}), confidence=0.125, lift=1.25)]),
 RelationRecord(items=frozenset({'shallot', 'light cream'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'shallot', 'light cream'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'shallot'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'shallot'}), items_add=frozenset({'light cream'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'soup', 'light cream'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'soup', 'light cream'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'soup'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'soup'}), items_add=frozenset({'light cream'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'low fat yogurt', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'low fat yogurt', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'low fat yogurt'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'low fat yogurt'}), confidence=0.125, lift=1.25)]),
 RelationRecord(items=frozenset({'meatballs', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'meatballs', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'meatballs'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'meatballs'}), confidence=0.125, lift=1.25)]),
 RelationRecord(items=frozenset({'milk', 'mineral water'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'milk', 'mineral water'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'milk'}), items_add=frozenset({'mineral water'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'mineral water'}), items_add=frozenset({'milk'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'milk', 'whole wheat rice'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'milk', 'whole wheat rice'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'milk'}), items_add=frozenset({'whole wheat rice'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'whole wheat rice'}), items_add=frozenset({'milk'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'whole wheat rice', 'mineral water'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'whole wheat rice', 'mineral water'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'mineral water'}), items_add=frozenset({'whole wheat rice'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'whole wheat rice'}), items_add=frozenset({'mineral water'}), confidence=1.0, lift=10.0)]),
 RelationRecord(items=frozenset({'shallot', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'shallot', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'shallot'}), confidence=0.125, lift=1.25), OrderedStatistic(items_base=frozenset({'shallot'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25)]),
 RelationRecord(items=frozenset({'soup', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'soup', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'soup'}), confidence=0.125, lift=1.25), OrderedStatistic(items_base=frozenset({'soup'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25)]),
 RelationRecord(items=frozenset({'nan', 'spaghetti'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'spaghetti'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'spaghetti'}), confidence=0.125, lift=1.25), OrderedStatistic(items_base=frozenset({'spaghetti'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25)]),
 RelationRecord(items=frozenset({'nan', 'turkey'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'turkey'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'turkey'}), confidence=0.125, lift=1.25), OrderedStatistic(items_base=frozenset({'turkey'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25)]),

**b) Adicione o valor de confiança para 0.2 e o lift para 3. Quantos registros foram retornados?**

In [11]:
rules = apriori(transactions, min_support=support, min_confidence=0.2, min_lift=3)

print('Número de registros:', len(list(rules)))

Número de registros: 50

**c) Adicione o código abaixo para poder visualizar melhor os dados. Faça comentário do que acontece em cada linha do código.**

In [15]:
A = []
B = []
suporte = []
confianca = []
lift = []

for resultado in results:
  s = resultado[1]
  result_rules = resultado[2]
  for result_rule in result_rules:
    a = list(result_rule[0])
    b = list(result_rule[1])
    c = result_rule[2]
    l = result_rule[3]
    A.append(a)
    B.append(b)
    suporte.append(s)
    confianca.append(c)
    lift.append(l)

rules_df = pd.DataFrame({'A': A, 'B': B, 'suporte': suporte, 'confianca': confianca, 'lift': lift})
rules_df.sort_values(by = 'lift', ascending = False)

,A,B,suporte,confianca,lift
3,[shrimp],[almonds],0.1,1.0,10.0
2,[almonds],[shrimp],0.1,1.0,10.0
5,[vegetables mix],[almonds],0.1,1.0,10.0
4,[almonds],[vegetables mix],0.1,1.0,10.0
19,[milk],[energy bar],0.1,1.0,10.0
...,...,...,...,...,...
111,[whole wheat pasta],"[nan, french fries]",0.1,1.0,5.0
112,"[nan, french fries]",[whole wheat pasta],0.1,0.5,5.0
113,"[whole wheat pasta, nan]",[french fries],0.1,1.0,5.0
157,[avocado],"[vegetables mix, almonds, shrimp]",0.1,0.5,5.0
168,"[vegetables mix, almonds, shrimp]",[avocado],0.1,1.0,5.0

**d) Ordene pelo valor de confiança para verificar qual regra tem maior confiabilidade. Qual o valor da regra com maior confiança?**

SE almonds ENTÃO avocado (100% de confiança).

In [18]:
rules_df.sort_values(by = 'confianca', ascending = False)

,A,B,suporte,confianca,lift
0,[almonds],[avocado],0.1,1.0,5.0
2,[almonds],[shrimp],0.1,1.0,10.0
3,[shrimp],[almonds],0.1,1.0,10.0
4,[almonds],[vegetables mix],0.1,1.0,10.0
11,[vegetables mix],[avocado],0.1,1.0,5.0
...,...,...,...,...,...
53,[avocado],"[vegetables mix, almonds]",0.1,0.5,5.0
10,[avocado],[vegetables mix],0.1,0.5,5.0
110,[french fries],"[whole wheat pasta, nan]",0.1,0.5,5.0
112,"[nan, french fries]",[whole wheat pasta],0.1,0.5,5.0
157,[avocado],"[vegetables mix, almonds, shrimp]",0.1,0.5,5.0